openapi: 3.0.0
paths:
  /users:
    get:
      operationId: UsersController_findAll
      summary: Get all users
      description: Get all users
      parameters: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
      tags:
        - Users
    post:
      operationId: UsersController_create
      summary: Create user
      description: Create a new user
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDto'
      responses:
        '201':
          description: The user has been created
        '400':
          description: Bad request
      tags:
        - Users
info:
  title: Home Library Service
  description: Home video, music and book library service
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        login:
          type: string
        password:
          type: string
      required:
        - id
        - login
        - password
    CreateUserDto:
      type: object
      properties:
        login:
          type: string
          minLength: 4
          maxLength: 20
        password:
          type: string
          pattern: /(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#\$%\^&\*])(?=.{8,})/
          minLength: 4
          maxLength: 20
      required:
        - login
        - password
