server:
  port: 4000

database:
  sqlite:
    database: "db.sqlite"

jwt:
  accessToken:
    secret: "secret123123"
    expiresIn: 3600
  refreshToken:
    secret: "secret312321"
    expiresIn: 4800

logger:
  level: "trace"
  transport:
    target: "pino-pretty"
    options:
      colorize: true
      singleLine: false
      messageFormat: "{msg} {req.method} {req.url} {res.statusCode}"
      ignore: "context,pid,hostname,req.id,res,responseTime,req.headers,req.remoteAddress,req.remotePort,req.method,req.url,"
      translateTime: true
      levelFirst: true
